### PR TITLE
CRM-173: Campaign names were not appearing in the report

### PR DESCRIPTION
**Pull request by monishdeb**
BEFORE
----------
camp aint

AFTER
----------
Screen Shot 2020-03-13 at 10 31 11 AM

### CODE REVIEW

**Comment by seamuslee001** [comment]
@monishdeb probably a separate issue but just looking at the report filters it seems the financial account one isn't showing correctly (not sure if its because of juggling different PRs about)
Report Filter fin account

**Comment by seamuslee001** [comment]
@monishdeb also if you filter on the campaign `Great Futures Start Here: Gift of Giving Campaign 2017` the rows listed count seems incorrect to me

**Comment by monishdeb** [comment]
Thanks @seamuslee001 for your feedback. re #1 it seems like it is only affecting report which is based on core contribution summary report, not happening with extendedSummary report (modfied version of core summary report). There might be some other civiextension which might be responsible for affecting the 'Financial Account' filter label. Can you please create a separate ticket for it?

re #2 thanks for catching this issue on using campaign filter. I have updated the PR and here's how it look now: 
Screen Shot 2020-03-13 at 11 20 53 AM

**Comment by seamuslee001** [comment]
@monishdeb confirmed the original issue and the row count is fixed

**Pull request merged**
